import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { HELP_CENTER_HOME_URL } from "@/lib/scraper/url";

type HomeFaqStats = {
  totalArticles: number;
  processedArticles: number;
  totalQuestions: number;
};

type HomeFaqProps = {
  stats: HomeFaqStats;
  categories: string[];
};

function HelpCenterLink({ children }: { children: React.ReactNode }) {
  return (
    <a
      href={HELP_CENTER_HOME_URL}
      target="_blank"
      rel="noopener noreferrer"
      className="text-violet-600 no-underline hover:opacity-80 dark:text-violet-400"
    >
      {children}
    </a>
  );
}

function formatCount(n: number) {
  return n.toLocaleString("en-CA");
}

export function HomeFaq({ stats, categories }: HomeFaqProps) {
  const categoryList =
    categories.length > 0
      ? categories.join(", ")
      : "Get Started, Move Money, Investing, Spending, and more";

  const items = [
    {
      value: "official",
      question: "Is this an official Wealthsimple product?",
      answer: (
        <p>
          No. WS Trivia is an independent learning project and is not affiliated with,
          endorsed by, or an official product of Wealthsimple.
        </p>
      ),
    },
    {
      value: "accuracy",
      question: "Are the quiz answers always accurate?",
      answer: (
        <p>
          Not necessarily. Questions are generated by an LLM from help center text, so
          they can be incomplete, outdated, or wrong. Always treat the official{" "}
          <HelpCenterLink>Wealthsimple help center</HelpCenterLink> as the source of
          truth. Each answer in the quiz includes a link back to the related article.
        </p>
      ),
    },
    {
      value: "content-volume",
      question: "How much help center content powers WS Trivia?",
      answer: (
        <p>
          WS Trivia tracks {formatCount(stats.totalArticles)}{" "}
          <HelpCenterLink>Wealthsimple help center</HelpCenterLink> articles. We’ve
          processed {formatCount(stats.processedArticles)} so far and generated{" "}
          {formatCount(stats.totalQuestions)} trivia questions from them. Coverage will
          grow as we process more.
        </p>
      ),
    },
    {
      value: "freshness",
      question: "How do you keep quizzes up to date?",
      answer: (
        <p>
          We periodically check help center articles for updates from Wealthsimple and
          regenerate facts and questions to keep the catalog fresh. There are no
          guarantees of real-time accuracy or complete coverage—always verify important
          details on the official <HelpCenterLink>help center</HelpCenterLink>.
        </p>
      ),
    },
    {
      value: "goal",
      question: "What is the goal of WS Trivia?",
      answer: (
        <p>
          Help people learn Wealthsimple products, services, and policies by playing short
          quizzes grounded in real help center articles. It is a low-pressure study tool
          for new hires, clients, and anyone exploring the platform—alongside the
          official docs, not instead of them.
        </p>
      ),
    },
    {
      value: "categories",
      question: "What are the categories and quizzes?",
      answer: (
        <p>
          Each quiz focuses on one help center topic—such as {categoryList}—or you can
          play an All categories quiz that mixes questions from every topic. Single-topic
          quizzes have 10 questions; the All categories quiz has 20.
        </p>
      ),
    },
    {
      value: "after-quiz",
      question: "What can I do after finishing a quiz?",
      answer: (
        <p>
          You will see your score and a{" "}
          <span className="text-foreground">review your misses</span> study sheet with
          the correct answers, explanations, and help center links. From there you can{" "}
          <span className="text-foreground">try again</span> (same questions,
          reshuffled), load <span className="text-foreground">new questions</span> from
          the same category, or go{" "}
          <span className="text-foreground">back to categories</span>.
        </p>
      ),
    },
    {
      value: "theme",
      question: "Is there a light and dark mode?",
      answer: (
        <p>
          Yes. Use the moon/sun toggle in the site header to switch between light and dark
          mode. Your preference is remembered for later visits.
        </p>
      ),
    },
    {
      value: "free",
      question: "Is WS Trivia free?",
      answer: (
        <p>Yes. You can play without creating an account or paying anything.</p>
      ),
    },
    {
      value: "privacy",
      question: "Do you collect personal data?",
      answer: (
        <p>
          No. There is no login, and we don’t collect your name, email, or other personal
          details.
        </p>
      ),
    },
    {
      value: "mobile",
      question: "Does this work on mobile?",
      answer: (
        <p>Yes. The site is built to work well on phones and desktops.</p>
      ),
    },
    {
      value: "wrong-question",
      question: "What if a question seems wrong?",
      answer: (
        <p>
          Trust the official <HelpCenterLink>help center</HelpCenterLink> over the quiz.
          Questions are reviewed as part of the publishing process, but mistakes can still
          slip through. When in doubt, follow the linked source article in the
          explanation.
        </p>
      ),
    },
    {
      value: "audience",
      question: "Who is this for?",
      answer: (
        <p>
          Anyone learning Wealthsimple—especially useful as a quick study aid for new team
          members, clients, or curious users who want to test what they know after reading
          help center articles.
        </p>
      ),
    },
  ];

  return (
    <section className="mt-16 sm:mt-24">
      <div className="grid gap-8 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.4fr)] lg:gap-12 xl:gap-16">
        <div className="lg:sticky lg:top-8 lg:self-start">
          <p className="text-muted-foreground text-xs font-medium tracking-wider uppercase">
            FAQ
          </p>
          <h2 className="mt-1 text-xl font-semibold tracking-tight sm:text-2xl">
            Common questions
          </h2>
          <p className="text-muted-foreground mt-3 max-w-sm text-sm leading-relaxed text-pretty sm:text-base">
            A quick look at what WS Trivia is, how the quizzes work, and what to expect
            when you play.
          </p>

          <div
            aria-hidden
            className="from-violet-500/15 via-violet-500/5 mt-8 hidden h-px w-24 bg-gradient-to-r to-transparent lg:block"
          />
        </div>

        <Accordion className="gap-3">
          {items.map((item) => (
            <AccordionItem
              key={item.value}
              value={item.value}
              className="border-border/50 overflow-hidden rounded-2xl border bg-card/60 shadow-sm backdrop-blur-sm transition-all duration-300 hover:border-border hover:bg-card data-open:border-violet-500/25 data-open:bg-gradient-to-br data-open:from-violet-500/[0.07] data-open:via-card/85 data-open:to-card/70 data-open:shadow-md data-open:shadow-violet-500/5 dark:data-open:border-violet-400/25 dark:data-open:from-violet-400/[0.12] dark:data-open:shadow-violet-400/5"
            >
              <AccordionTrigger className="rounded-none px-5 py-4 text-[0.9375rem] leading-snug sm:px-6 sm:py-5 sm:text-base">
                {item.question}
              </AccordionTrigger>
              <AccordionContent className="px-5 pb-5 text-[0.9375rem] sm:px-6 sm:pb-6 sm:text-base">
                {item.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}
